FROM --platform=${BUILDPLATFORM} golang:1.18.1-alpine3.14 as builder

WORKDIR /workspace

COPY go.mod go.sum /workspace/
RUN go mod download

COPY cmd /workspace/cmd
COPY private /workspace/private

ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  go build -ldflags "-s -w" -trimpath -o /go/bin/protoc-gen-api-linter ./cmd/protoc-gen-api-linter

FROM --platform=${TARGETPLATFORM} alpine:3.18.0

RUN apk add --update --no-cache \
    ca-certificates \
    git \
    openssh-client && \
  rm -rf /var/cache/apk/*

COPY --from=builder /go/bin/protoc-gen-api-linter /usr/local/bin/protoc-gen-api-linter

ENTRYPOINT ["/usr/local/bin/protoc-gen-api-linter"]
